import {
  ServiceForServiceDetail,
  ServiceFront,
  SubsNOp,
  SubsNOpFront,
} from '../../../types';

export const SUBS_LIST: Array<SubsNOpFront> = [
  {
    id: '1',
    case: 0,
    folderKeyName: 'first',
    nameKr: '국문',
    nameEn: '영문',
    directLink: '',
    keyName: 'key_subs_netflix_basic',
    currency: 'KRW',
    pricePlan: 5000,
    periodUnit: 1,
    periodType: 'MONTHLY',
    memo: '',
    serviceId: '',
    promotion: '',
  },
  {
    id: '2',
    case: 0,
    folderKeyName: 'first',
    directLink: '',
    keyName: 'key_subs_netflix_pro',
    nameKr: '국문',
    nameEn: '영문',
    currency: 'KRW',
    pricePlan: 120000,
    periodUnit: 1,
    periodType: 'YEARLY',
    memo: '',
    serviceId: '',
    promotion: '',
  },
  {
    id: '3',
    case: 0,
    folderKeyName: '',
    directLink: '',
    keyName: 'key_subs_netflix_special',
    nameKr: '국문',
    nameEn: '영문',
    currency: 'USD',
    pricePlan: 110.0,
    periodUnit: 1,
    periodType: 'DAILY',
    memo: '',
    serviceId: '',
    promotion: '',
  },
];

export const SERVICE_DETAIL: ServiceFront = {
  id: '12341',
  keyName: 'NETFLIX',
  name: 'Netflix',
  nameKr: '넷플릭스',
  thumbnail: 'https://s3.amazonaws.com/uifaces/faces/twitter/kylefrost/128.jpg',
  image: 'https://s3.amazonaws.com/uifaces/faces/twitter/kylefrost/128.jpg',
  homepage: 'netflix.com',
  memo:
    '넷플릭스 입니다. 넷플릭스 입니다. 넷플릭스 입니다. 넷플릭스 입니다. 넷플릭스 입니다. 넷플릭스 입니다. 넷플릭스 입니다. 넷플릭스 입니다. 넷플릭스 입니다. ',
  iosAppStoreUrl: 'netflix.com',
  androidPlayStoreUrl: 'netflix.com',
  categoryId: '',
  serviceGroupId: '',
};
