import { CategoryTableLabel, ServiceFront } from '../../../types';

import faker from 'faker';

// This function is being used to create below SERVICE_LIST

// const createFakeServiceList = () => {
//   let list: Array<Service> = [];
//   const length = 50;
//   for (let i = 0; i < length; i++) {
//     list.push({
//       id: faker.random.number().toString(),
//       keyName: faker.company.companyName(),
//       name: faker.company.companyName(),
//       nameKr: faker.company.companyName(),
//       thumbnail: faker.image.avatar(),
//       image: faker.image.business(),
//       iosAppStoreUrl: faker.internet.url(),
//       androidPlayStoreUrl: faker.internet.url(),
//       homepage: faker.internet.url(),
//       memo: faker.lorem.paragraph(),
//       categoryId: faker.random.number().toString(),
//       serviceGroupId: faker.random.number().toString(),
//     });
//   }
//   // you can copy the result of it and paste it to 'ServiceList'
//   console.log('fake service list', JSON.stringify(list, null, 2));
//   return list;
// };
// createFakeServiceList();

export const SERVICE_LIST: Array<ServiceFront> = [
  {
    id: '45265',
    keyName: 'Schmeler - Simonis',
    name: 'Moore and Sons',
    nameKr: 'Kautzer - Heller',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/stayuber/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'https://neil.net',
    androidPlayStoreUrl: 'https://wade.com',
    homepage: 'https://avis.com',
    memo:
      'Dolore dolor nisi ullam ducimus eveniet non adipisci provident. Reprehenderit voluptatem dolor. Suscipit optio beatae. Repudiandae maxime quia ipsam veritatis sint non. Ut est nihil sit autem aut.',
    categoryId: '43295',
    serviceGroupId: '17575',
  },
  {
    id: '28620',
    keyName: 'Rau, Johnston and Smitham',
    name: "O'Reilly, Borer and Wolff",
    nameKr: 'Turner - Kuphal',
    thumbnail: 'https://s3.amazonaws.com/uifaces/faces/twitter/abdots/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'https://justice.name',
    androidPlayStoreUrl: 'https://aurelie.com',
    homepage: 'http://paula.com',
    memo:
      'Similique ut voluptatem iste debitis vel. Enim eaque autem. Quaerat placeat at nemo ea et explicabo molestiae est. Quia adipisci reiciendis dolores error non. Ea laudantium quo deserunt aliquam et est reiciendis.',
    categoryId: '61692',
    serviceGroupId: '9920',
  },
  {
    id: '22283',
    keyName: 'Bayer, Windler and King',
    name: 'Bartell - Windler',
    nameKr: 'Williamson LLC',
    thumbnail: 'https://s3.amazonaws.com/uifaces/faces/twitter/artvavs/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'https://breanna.name',
    androidPlayStoreUrl: 'https://estell.com',
    homepage: 'https://rahsaan.org',
    memo:
      'Rem inventore molestiae accusantium sunt quisquam deserunt. Dolor optio quis distinctio occaecati. Esse dolor repellat in tempora explicabo dolorem reprehenderit necessitatibus nulla. Cum ea natus vero. Et a molestias omnis ut explicabo.',
    categoryId: '52941',
    serviceGroupId: '80913',
  },
  {
    id: '66822',
    keyName: 'McGlynn LLC',
    name: 'Rutherford, Daugherty and Fisher',
    nameKr: 'Weber, Corwin and Bergstrom',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/snowwrite/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'https://korey.name',
    androidPlayStoreUrl: 'http://matteo.name',
    homepage: 'https://cassidy.info',
    memo:
      'Ab aliquam quia saepe. Commodi velit labore laborum at occaecati. Quia adipisci facere soluta ex. Repudiandae voluptatem aperiam. Dicta quisquam ullam aut.',
    categoryId: '754',
    serviceGroupId: '24093',
  },
  {
    id: '43768',
    keyName: 'Effertz, Jerde and Lang',
    name: 'Jenkins Group',
    nameKr: 'Konopelski LLC',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/amywebbb/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'https://janiya.name',
    androidPlayStoreUrl: 'http://jarvis.com',
    homepage: 'https://arlo.com',
    memo:
      'Magni reiciendis illo excepturi sit pariatur repellat soluta temporibus. Iste quasi sapiente. Aspernatur exercitationem corrupti facilis impedit. Nesciunt error est. Soluta sed quas. Et aut explicabo minus doloremque ut.',
    categoryId: '70824',
    serviceGroupId: '22389',
  },
  {
    id: '40377',
    keyName: 'Zemlak - Bosco',
    name: 'Keeling, Jones and Hudson',
    nameKr: 'Nitzsche - Crist',
    thumbnail: 'https://s3.amazonaws.com/uifaces/faces/twitter/pifagor/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'http://amos.net',
    androidPlayStoreUrl: 'https://etha.net',
    homepage: 'http://isaiah.biz',
    memo:
      'Quam recusandae aut id omnis aspernatur enim dolorem. Et nobis ut debitis sit. Omnis dolorem velit provident ab.',
    categoryId: '35070',
    serviceGroupId: '78300',
  },
  {
    id: '9173',
    keyName: 'Gleason Inc',
    name: 'Wehner - Parisian',
    nameKr: 'Kling - Watsica',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/sdidonato/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'https://aniyah.biz',
    androidPlayStoreUrl: 'https://kaia.net',
    homepage: 'https://mallory.org',
    memo:
      'Ipsa modi dolorem quam. At vel nisi ullam voluptatum. Aliquid corrupti molestiae sunt nihil aut optio quis laudantium. Magnam sunt est error ratione laborum eos mollitia rerum. Asperiores id ut quasi earum excepturi eos omnis in.',
    categoryId: '73843',
    serviceGroupId: '50294',
  },
  {
    id: '94720',
    keyName: 'Cormier - Hegmann',
    name: 'Hudson - Walker',
    nameKr: 'Hegmann - Legros',
    thumbnail: 'https://s3.amazonaws.com/uifaces/faces/twitter/8d3k/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'https://deangelo.biz',
    androidPlayStoreUrl: 'https://ottis.net',
    homepage: 'https://dixie.com',
    memo:
      'Nemo animi qui adipisci soluta occaecati. Et numquam perspiciatis. Soluta sit sunt quia quaerat qui quaerat. Id vero illum voluptates rem non ut ipsam. Beatae deleniti voluptatibus dignissimos nemo nobis ut sit officiis unde. Natus non saepe vero qui in libero rerum ea.',
    categoryId: '73718',
    serviceGroupId: '42469',
  },
  {
    id: '35328',
    keyName: 'Greenfelder, Senger and Dickens',
    name: "Pacocha - O'Kon",
    nameKr: 'Lesch - Ullrich',
    thumbnail: 'https://s3.amazonaws.com/uifaces/faces/twitter/n3dmax/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'https://tavares.biz',
    androidPlayStoreUrl: 'http://lupe.net',
    homepage: 'https://jules.org',
    memo:
      'Voluptas animi doloribus ducimus perferendis nihil et doloribus aut. Laudantium qui aut ea minus fugit vero sit. Explicabo qui omnis exercitationem vitae minus. Et ut qui neque eius earum et et eum et.',
    categoryId: '19554',
    serviceGroupId: '77085',
  },
  {
    id: '1369',
    keyName: 'Murphy and Sons',
    name: 'Leannon - Fritsch',
    nameKr: 'Grady, Miller and Funk',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/codysanfilippo/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'http://garry.net',
    androidPlayStoreUrl: 'https://salvatore.biz',
    homepage: 'http://johnathon.name',
    memo:
      'Vel beatae rerum unde expedita mollitia doloribus quia. In laborum qui architecto necessitatibus quis qui dicta est numquam. Dignissimos officiis magnam aliquam provident dolores. Itaque perferendis aut nesciunt et non delectus nam qui ut. Voluptas molestias doloremque placeat ipsum. Rem dolores ut corporis.',
    categoryId: '92045',
    serviceGroupId: '23607',
  },
  {
    id: '84868',
    keyName: 'Schamberger, Cartwright and Beer',
    name: 'Williamson, Ward and Runolfsdottir',
    nameKr: 'Leuschke, Gutmann and Kuhlman',
    thumbnail: 'https://s3.amazonaws.com/uifaces/faces/twitter/r_oy/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'http://maeve.org',
    androidPlayStoreUrl: 'https://tamia.com',
    homepage: 'https://karen.biz',
    memo:
      'Doloremque quibusdam quam sed mollitia et dicta omnis sequi. Cum in unde. Quaerat eius expedita doloribus et. Sint et et.',
    categoryId: '4563',
    serviceGroupId: '70579',
  },
  {
    id: '24155',
    keyName: 'Cruickshank Inc',
    name: 'Larkin LLC',
    nameKr: 'Strosin LLC',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/uberschizo/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'https://jeffery.biz',
    androidPlayStoreUrl: 'http://braeden.name',
    homepage: 'https://verda.info',
    memo:
      'Mollitia velit sequi corrupti sequi fugiat sequi nesciunt. Quibusdam reiciendis voluptatibus et consequatur rerum ipsa ipsum quas. Et totam in dolorem nemo et odit. Est quo et deserunt.',
    categoryId: '64911',
    serviceGroupId: '39422',
  },
  {
    id: '22618',
    keyName: 'Bosco, Breitenberg and Jenkins',
    name: "Cassin - O'Keefe",
    nameKr: 'Bogan Group',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/abdullindenis/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'https://braeden.org',
    androidPlayStoreUrl: 'https://devin.info',
    homepage: 'https://kaylin.net',
    memo:
      'Laborum debitis quae rerum quam exercitationem id quas. Maiores ut facere laborum sequi. Rerum esse culpa consequuntur. Sequi est fugit libero. Perspiciatis saepe aut. Minima quia ut necessitatibus quia voluptatem aliquam voluptates quia hic.',
    categoryId: '48505',
    serviceGroupId: '812',
  },
  {
    id: '99794',
    keyName: 'Botsford, Wehner and Shanahan',
    name: 'Kirlin - Heaney',
    nameKr: 'Schmidt - Tillman',
    thumbnail: 'https://s3.amazonaws.com/uifaces/faces/twitter/kimcool/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'http://kendall.org',
    androidPlayStoreUrl: 'http://rebeca.net',
    homepage: 'https://bailey.info',
    memo:
      'Est ut iusto dolorem assumenda est quaerat. Cum tempore aperiam voluptatem explicabo minima dolores. Consequatur ipsa in placeat earum molestiae sunt adipisci occaecati. Repellat et quis quas quia.',
    categoryId: '85978',
    serviceGroupId: '67618',
  },
  {
    id: '78527',
    keyName: 'Hirthe Inc',
    name: 'Grimes - Trantow',
    nameKr: 'Gutkowski, Moen and Von',
    thumbnail: 'https://s3.amazonaws.com/uifaces/faces/twitter/meln1ks/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'https://tierra.info',
    androidPlayStoreUrl: 'https://deon.biz',
    homepage: 'https://shaina.net',
    memo:
      'Totam sint officiis et debitis laborum nobis dolore rerum. Repudiandae rerum animi aperiam perferendis earum. Exercitationem sit aut sit qui sed doloremque laboriosam vitae. Et consequatur natus corrupti sint dolores velit ipsum voluptas qui.',
    categoryId: '89562',
    serviceGroupId: '25280',
  },
  {
    id: '25956',
    keyName: 'Gottlieb - Skiles',
    name: 'Rempel and Sons',
    nameKr: 'Weber and Sons',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/robinlayfield/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'https://clementina.net',
    androidPlayStoreUrl: 'https://laury.biz',
    homepage: 'https://kyra.name',
    memo:
      'Sapiente quia reiciendis non laborum officiis architecto fugiat. Qui quo enim quaerat et dolorum sequi id dignissimos. Sequi molestias dolorum quia est iusto est est qui temporibus. Magnam numquam sapiente.',
    categoryId: '32252',
    serviceGroupId: '90674',
  },
  {
    id: '69542',
    keyName: 'Grimes - Bauch',
    name: 'Hartmann, Krajcik and Nader',
    nameKr: 'Schinner, Becker and Reinger',
    thumbnail: 'https://s3.amazonaws.com/uifaces/faces/twitter/sawrb/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'http://alexanne.biz',
    androidPlayStoreUrl: 'http://moses.com',
    homepage: 'http://mittie.name',
    memo:
      'Debitis sit quis pariatur et dolor possimus. Et necessitatibus libero fugit rerum eligendi. Officia aut occaecati porro repellat.',
    categoryId: '89105',
    serviceGroupId: '71333',
  },
  {
    id: '28375',
    keyName: 'Tremblay, Kassulke and Runte',
    name: 'Block - Lubowitz',
    nameKr: "O'Conner, Torp and Mraz",
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/robinlayfield/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'http://xavier.info',
    androidPlayStoreUrl: 'http://clark.name',
    homepage: 'http://kurt.biz',
    memo:
      'Quam commodi consequatur saepe placeat ipsa veniam eligendi consequatur odit. Est culpa unde consequatur dolorem. Facere maxime ut laboriosam vero ut voluptatem sequi.',
    categoryId: '83442',
    serviceGroupId: '30589',
  },
  {
    id: '8076',
    keyName: 'Bergstrom, Carter and Kertzmann',
    name: 'Stehr Inc',
    nameKr: 'Feest and Sons',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/dutchnadia/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'http://freddie.info',
    androidPlayStoreUrl: 'http://carley.net',
    homepage: 'https://sid.com',
    memo:
      'Et culpa laudantium excepturi nisi corrupti dolorum provident repellat hic. Aperiam placeat laudantium. Sequi labore et est quasi voluptatem nulla aut et. Voluptatem quasi saepe impedit adipisci autem.',
    categoryId: '40820',
    serviceGroupId: '31125',
  },
  {
    id: '45473',
    keyName: 'Will, Feeney and Kilback',
    name: 'Pfannerstill LLC',
    nameKr: 'Cummings, Stiedemann and Jenkins',
    thumbnail: 'https://s3.amazonaws.com/uifaces/faces/twitter/zaki3d/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'https://onie.com',
    androidPlayStoreUrl: 'http://luz.info',
    homepage: 'http://bailee.biz',
    memo:
      'Delectus vel tenetur dolores maxime officia qui atque eligendi. Debitis veniam sint autem dolores. Ipsam vel adipisci ad saepe a. Possimus amet qui vitae recusandae asperiores sed quis magni. Amet asperiores iusto autem rerum voluptas est vel nam.',
    categoryId: '48462',
    serviceGroupId: '41077',
  },
  {
    id: '78310',
    keyName: 'Gislason, Jakubowski and Carroll',
    name: 'Eichmann Group',
    nameKr: 'Will LLC',
    thumbnail: 'https://s3.amazonaws.com/uifaces/faces/twitter/kerem/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'https://rylan.biz',
    androidPlayStoreUrl: 'http://sheldon.info',
    homepage: 'https://shayna.name',
    memo:
      'Aliquam molestiae voluptatibus quod corporis dignissimos alias. Doloremque mollitia ut corporis facilis aut esse. Explicabo doloremque hic et. Ut consequuntur voluptatem itaque ea nostrum velit. Nulla suscipit hic provident in aut et dolor et corporis.',
    categoryId: '79200',
    serviceGroupId: '11353',
  },
  {
    id: '68819',
    keyName: 'Tremblay - Vandervort',
    name: 'Rogahn LLC',
    nameKr: 'Halvorson Inc',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/iamgarth/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'http://piper.com',
    androidPlayStoreUrl: 'http://nova.name',
    homepage: 'http://jeanne.name',
    memo:
      'Quia sit et voluptas in suscipit eos. At quidem nam voluptates occaecati ea earum iste. Earum voluptate qui labore quia cupiditate. Dolorem repellendus aperiam error sunt error nihil.',
    categoryId: '77703',
    serviceGroupId: '60639',
  },
  {
    id: '97928',
    keyName: 'Gleason Inc',
    name: 'Stamm - Schroeder',
    nameKr: 'Greenfelder and Sons',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/robbschiller/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'http://adah.name',
    androidPlayStoreUrl: 'https://kamren.biz',
    homepage: 'http://michael.name',
    memo:
      'Similique fuga quo rerum facilis sed dolor. Voluptas eligendi facere aperiam vel quos dignissimos et. Et aspernatur iusto. Nemo rem praesentium.',
    categoryId: '64231',
    serviceGroupId: '1854',
  },
  {
    id: '13285',
    keyName: 'Blick - Aufderhar',
    name: 'Ortiz Group',
    nameKr: 'Hodkiewicz - Howe',
    thumbnail: 'https://s3.amazonaws.com/uifaces/faces/twitter/uxward/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'https://eleanore.name',
    androidPlayStoreUrl: 'http://madison.biz',
    homepage: 'http://garrick.info',
    memo:
      'Maxime enim iusto. Quisquam est dolore magni dolor repudiandae. Accusamus consequuntur ut non quidem.',
    categoryId: '63494',
    serviceGroupId: '32341',
  },
  {
    id: '77287',
    keyName: 'Schimmel and Sons',
    name: 'Howell LLC',
    nameKr: 'Dickens Group',
    thumbnail: 'https://s3.amazonaws.com/uifaces/faces/twitter/dannol/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'https://meagan.com',
    androidPlayStoreUrl: 'https://ardith.com',
    homepage: 'http://laury.com',
    memo:
      'Mollitia at sunt ipsa sint accusamus. Consequuntur quia soluta et. Nihil architecto culpa sit. Alias ea ducimus cupiditate accusantium laudantium facere iure provident.',
    categoryId: '40893',
    serviceGroupId: '2729',
  },
  {
    id: '8053',
    keyName: 'Barrows - Harber',
    name: 'Kshlerin, Ryan and Schiller',
    nameKr: 'Kessler - Kutch',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/_pedropinho/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'https://scot.biz',
    androidPlayStoreUrl: 'https://annetta.com',
    homepage: 'http://jacklyn.info',
    memo:
      'Perspiciatis necessitatibus quaerat ut. Illo fuga ut numquam delectus aut. Explicabo alias earum nesciunt a quis minima distinctio est. Nemo est velit quo illo necessitatibus odit officiis ea. Dicta quia molestias vitae voluptas eveniet iure qui officiis.',
    categoryId: '88429',
    serviceGroupId: '84073',
  },
  {
    id: '47899',
    keyName: 'Kovacek - Tillman',
    name: 'Satterfield LLC',
    nameKr: 'Senger Inc',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/nitinhayaran/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'http://kimberly.name',
    androidPlayStoreUrl: 'https://delmer.biz',
    homepage: 'http://bailey.net',
    memo:
      'Et quo et eius officiis in. Aut quam magnam dolorum sint itaque quis occaecati. Assumenda sint quas iusto unde quia vel in qui.',
    categoryId: '77754',
    serviceGroupId: '62118',
  },
  {
    id: '74840',
    keyName: 'Trantow, Ledner and Kovacek',
    name: 'Powlowski - Hansen',
    nameKr: 'Sauer, MacGyver and Lind',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/bungiwan/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'https://juston.org',
    androidPlayStoreUrl: 'https://alia.name',
    homepage: 'https://davin.info',
    memo:
      'Odit nulla sapiente et commodi fugit nemo natus. Sunt excepturi aut officia deserunt corrupti sit possimus repudiandae error. Amet at dolorum deleniti voluptatem reiciendis.',
    categoryId: '27520',
    serviceGroupId: '28860',
  },
  {
    id: '60225',
    keyName: 'Crona, Lubowitz and Funk',
    name: 'Hartmann, Klocko and White',
    nameKr: 'Balistreri, Kub and Koch',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/herkulano/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'https://mabelle.org',
    androidPlayStoreUrl: 'http://denis.biz',
    homepage: 'http://susana.biz',
    memo:
      'Libero quia velit aut dolore. Dolor aliquid voluptas non nesciunt qui corrupti sunt. Magnam earum voluptatem odio tempore tenetur ipsa. Quis aliquam ea ut expedita iure totam corporis accusantium. Consequuntur error voluptatibus dolor sit aperiam corrupti velit.',
    categoryId: '51509',
    serviceGroupId: '35557',
  },
  {
    id: '61780',
    keyName: 'Sporer - Torphy',
    name: 'Stamm - Heidenreich',
    nameKr: 'Schiller LLC',
    thumbnail: 'https://s3.amazonaws.com/uifaces/faces/twitter/kinday/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'http://hattie.biz',
    androidPlayStoreUrl: 'https://marquise.name',
    homepage: 'http://khalil.net',
    memo:
      'Quo ab ut aperiam est sequi dolore. Vitae ullam facere natus vero veritatis aperiam quos iure. Recusandae molestiae ea explicabo. Id quasi ullam veritatis magnam delectus. Ut doloribus qui et harum quia at aliquid provident. Cumque illum corporis labore nulla.',
    categoryId: '74781',
    serviceGroupId: '71782',
  },
  {
    id: '4940',
    keyName: 'Keeling and Sons',
    name: 'Bosco and Sons',
    nameKr: 'Kiehn Group',
    thumbnail: 'https://s3.amazonaws.com/uifaces/faces/twitter/nacho/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'https://jalen.name',
    androidPlayStoreUrl: 'http://florida.info',
    homepage: 'http://gregoria.com',
    memo:
      'Aspernatur omnis quis similique. Vel rerum quos eveniet. Aperiam ea repellendus asperiores reprehenderit quo adipisci quia vero. Repudiandae omnis et sint enim omnis reprehenderit magni autem minima.',
    categoryId: '32787',
    serviceGroupId: '54312',
  },
  {
    id: '90004',
    keyName: 'Jenkins LLC',
    name: 'Franecki, Price and Gibson',
    nameKr: 'Wilkinson, Schaden and Hudson',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/taylorling/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'http://winston.name',
    androidPlayStoreUrl: 'https://eusebio.org',
    homepage: 'http://dejah.org',
    memo:
      'Blanditiis qui dicta. Consequatur omnis consectetur voluptatem vel quisquam. Animi est et hic asperiores minus pariatur dolores.',
    categoryId: '79728',
    serviceGroupId: '93686',
  },
  {
    id: '46104',
    keyName: 'Predovic - Considine',
    name: 'Huel Inc',
    nameKr: 'Keeling - Cruickshank',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/tom_even/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'http://kameron.com',
    androidPlayStoreUrl: 'https://jonatan.biz',
    homepage: 'http://river.org',
    memo:
      'Ut et error ducimus tenetur explicabo molestias. Consequuntur earum fugit ut ex aliquam at esse. Commodi accusamus corporis aperiam in perferendis itaque autem voluptatem cupiditate.',
    categoryId: '92125',
    serviceGroupId: '49582',
  },
  {
    id: '64955',
    keyName: 'McKenzie LLC',
    name: 'Daniel - Huel',
    nameKr: 'Ledner - Swaniawski',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/charliegann/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'https://rebeka.com',
    androidPlayStoreUrl: 'http://annabell.name',
    homepage: 'https://emory.biz',
    memo:
      'Numquam cum laboriosam id eligendi recusandae. Dolorum facere eius voluptate. Porro autem exercitationem. Et magnam reprehenderit magnam repudiandae nihil necessitatibus possimus ut et.',
    categoryId: '98352',
    serviceGroupId: '69117',
  },
  {
    id: '90647',
    keyName: 'Bruen - Quigley',
    name: 'Labadie - Kuphal',
    nameKr: 'Langworth Group',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/christianoliff/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'http://genevieve.net',
    androidPlayStoreUrl: 'http://moses.info',
    homepage: 'http://dianna.info',
    memo:
      'Deserunt nemo laboriosam et optio. Ut aut et at laboriosam repellat deleniti veniam hic. Ea velit cumque ad sit nostrum aperiam animi. Aperiam maiores eum et non reiciendis.',
    categoryId: '81318',
    serviceGroupId: '50678',
  },
  {
    id: '43136',
    keyName: 'Waelchi - Ferry',
    name: "Rosenbaum - O'Kon",
    nameKr: 'Johns, Kihn and Prohaska',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/curiousoffice/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'http://anne.name',
    androidPlayStoreUrl: 'http://casandra.biz',
    homepage: 'https://ron.org',
    memo:
      'Soluta tempore minima magni eaque ut veritatis recusandae. Quaerat itaque ratione voluptatem voluptas ea vel. Dolor atque quisquam maiores. Consequatur voluptate illum cupiditate.',
    categoryId: '46504',
    serviceGroupId: '25259',
  },
  {
    id: '52829',
    keyName: 'Wyman, Kilback and Heaney',
    name: 'Jacobson LLC',
    nameKr: 'Weber, Ferry and Stanton',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/carlosjgsousa/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'http://sonny.biz',
    androidPlayStoreUrl: 'https://dorian.biz',
    homepage: 'https://maurice.com',
    memo:
      'Id occaecati est laborum voluptas. Nihil consequatur odio. Expedita qui ullam.',
    categoryId: '35432',
    serviceGroupId: '4544',
  },
  {
    id: '4305',
    keyName: 'Medhurst, Ward and Beatty',
    name: 'Jacobson - Fahey',
    nameKr: 'Stracke, Beer and Feil',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/darcystonge/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'https://arielle.com',
    androidPlayStoreUrl: 'https://hosea.biz',
    homepage: 'https://lera.net',
    memo:
      'Consequatur et quidem corrupti. Ipsam nam nesciunt neque quia autem quibusdam voluptates non. Illo molestias et. Corrupti est dolor ut ut quisquam iure sunt neque quo. Perspiciatis et illo consequatur esse illo fugiat ratione pariatur.',
    categoryId: '61240',
    serviceGroupId: '46417',
  },
  {
    id: '81743',
    keyName: 'Hammes LLC',
    name: 'Walter LLC',
    nameKr: 'Adams and Sons',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/anthonysukow/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'https://paula.net',
    androidPlayStoreUrl: 'http://rhoda.info',
    homepage: 'http://aryanna.com',
    memo:
      'Nam dignissimos ducimus. Beatae soluta et molestiae nemo. Deleniti fuga consectetur facere autem nisi id. Ducimus deleniti harum debitis voluptas aut sint. Non esse corporis libero soluta et doloremque maiores nobis dolor.',
    categoryId: '74112',
    serviceGroupId: '86537',
  },
  {
    id: '53659',
    keyName: 'Jerde - Abshire',
    name: 'Eichmann and Sons',
    nameKr: 'Kirlin - Sanford',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/helderleal/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'https://shaina.net',
    androidPlayStoreUrl: 'http://audreanne.com',
    homepage: 'https://layne.info',
    memo:
      'Qui fugit reprehenderit ipsam ducimus voluptates asperiores. Quaerat aut modi accusantium ullam aut in. Quis sint occaecati et a.',
    categoryId: '54598',
    serviceGroupId: '19611',
  },
  {
    id: '71310',
    keyName: 'McLaughlin - Schoen',
    name: 'Luettgen Group',
    nameKr: 'Gleason LLC',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/madebybrenton/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'http://ahmad.org',
    androidPlayStoreUrl: 'http://maureen.org',
    homepage: 'http://chelsea.name',
    memo:
      'Deserunt sint consequuntur sit odit. Est et ut id dicta voluptatem ab eveniet. Corrupti mollitia accusantium sint qui velit sunt libero quam. Ex esse dolor est dicta reprehenderit ab est dolorum soluta. Veritatis officia in natus ipsa qui tempore et numquam.',
    categoryId: '57702',
    serviceGroupId: '58242',
  },
  {
    id: '52176',
    keyName: 'Prosacco LLC',
    name: 'Hettinger LLC',
    nameKr: 'Kerluke Group',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/bargaorobalo/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'https://margarita.biz',
    androidPlayStoreUrl: 'https://desiree.com',
    homepage: 'http://viola.biz',
    memo:
      'Recusandae quia ipsum eius consequatur qui. Sint dolor soluta. Id aut in neque officia rerum quis non iure et.',
    categoryId: '59639',
    serviceGroupId: '80055',
  },
  {
    id: '6140',
    keyName: 'Torp Group',
    name: "Bosco - O'Hara",
    nameKr: 'Reinger, Jaskolski and Doyle',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/hjartstrorn/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'http://ransom.org',
    androidPlayStoreUrl: 'https://carli.name',
    homepage: 'https://samir.net',
    memo:
      'Reiciendis deleniti dolorum nihil. Voluptate et et. Laboriosam deleniti et maxime.',
    categoryId: '40205',
    serviceGroupId: '77588',
  },
  {
    id: '94909',
    keyName: 'Hamill, Ankunding and Keebler',
    name: 'Jacobs, Rodriguez and Klein',
    nameKr: 'Abbott and Sons',
    thumbnail: 'https://s3.amazonaws.com/uifaces/faces/twitter/muringa/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'https://magali.com',
    androidPlayStoreUrl: 'http://euna.info',
    homepage: 'http://brad.org',
    memo:
      'Delectus harum optio id quidem qui ad maiores recusandae magnam. Illo rerum at quis. Sit distinctio quam voluptatem iste culpa mollitia nulla. Blanditiis id aut odio.',
    categoryId: '62570',
    serviceGroupId: '91048',
  },
  {
    id: '9392',
    keyName: 'Treutel - Heidenreich',
    name: 'Cole - Torphy',
    nameKr: 'Hettinger - Blick',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/jeremymouton/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'https://vincenzo.info',
    androidPlayStoreUrl: 'https://jimmie.name',
    homepage: 'https://breanne.info',
    memo:
      'Incidunt numquam error officiis. Fugit molestiae quas enim molestias sit esse. Ea inventore et atque. Exercitationem quod vitae. Quia consequatur nihil quam ducimus excepturi maiores vitae dolorem.',
    categoryId: '66668',
    serviceGroupId: '24195',
  },
  {
    id: '60013',
    keyName: 'Muller - Satterfield',
    name: 'Gorczany - Turcotte',
    nameKr: 'Rodriguez - Block',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/felipecsl/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'http://daniella.org',
    androidPlayStoreUrl: 'https://murphy.com',
    homepage: 'http://susie.biz',
    memo:
      'Asperiores ipsam quod eligendi. Est perspiciatis quaerat eveniet ut ut voluptates labore. Omnis magnam voluptatibus. Deserunt est libero qui et et inventore rerum nobis quo. Alias dolorum aut dolore voluptas omnis cupiditate impedit quos.',
    categoryId: '76758',
    serviceGroupId: '87464',
  },
  {
    id: '59901',
    keyName: 'Rutherford, Gleichner and Harber',
    name: 'Gislason, Cummerata and Quigley',
    nameKr: 'Bergstrom, Douglas and Mraz',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/sethlouey/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'https://johathan.biz',
    androidPlayStoreUrl: 'https://caesar.biz',
    homepage: 'http://sadye.info',
    memo:
      'Nisi corporis quo repellendus pariatur eos et. Sunt aut asperiores repellat sit et rerum aperiam illo. Corrupti quae quibusdam quibusdam deserunt ab. Hic tempore unde facilis temporibus voluptatibus nemo vero. Corporis eligendi corrupti ut dolorem beatae. Itaque adipisci voluptatem omnis.',
    categoryId: '76537',
    serviceGroupId: '21543',
  },
  {
    id: '61640',
    keyName: 'Wiegand Inc',
    name: 'Wyman - Jaskolski',
    nameKr: 'Keebler - Stokes',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/doronmalki/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'http://jaylan.name',
    androidPlayStoreUrl: 'https://isabell.info',
    homepage: 'http://celestine.biz',
    memo:
      'Illo debitis eius culpa libero nihil. Dicta asperiores ut voluptate et et eos. Ut quaerat eos eum voluptatem autem quod provident architecto. Voluptatem omnis voluptas aut. Ut qui facilis natus molestiae ut. Sint dolorem voluptatem qui numquam repudiandae omnis.',
    categoryId: '53639',
    serviceGroupId: '12533',
  },
  {
    id: '86733',
    keyName: 'Ledner - Lockman',
    name: 'Tromp - Beer',
    nameKr: 'Reinger - Schmidt',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/kennyadr/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'http://naomi.com',
    androidPlayStoreUrl: 'https://iliana.biz',
    homepage: 'https://titus.net',
    memo:
      'Quisquam vitae veritatis magni inventore in autem nihil culpa sapiente. Excepturi qui fuga voluptas id qui doloremque quasi ratione libero. Suscipit ratione sit.',
    categoryId: '45619',
    serviceGroupId: '72247',
  },
  {
    id: '45693',
    keyName: 'Bins - Gutkowski',
    name: 'Collins - Steuber',
    nameKr: 'Heaney - Ledner',
    thumbnail:
      'https://s3.amazonaws.com/uifaces/faces/twitter/estebanuribe/128.jpg',
    image: 'http://lorempixel.com/640/480/business',
    iosAppStoreUrl: 'https://sigrid.biz',
    androidPlayStoreUrl: 'http://tristian.com',
    homepage: 'http://muriel.net',
    memo:
      'Excepturi sit odit soluta deleniti error quas rerum. Sint dolor natus rerum eum. Sint occaecati nam architecto aliquid et aspernatur velit. Adipisci beatae cupiditate excepturi ut facilis. Alias vitae dolorum ipsam minus voluptatem aut sed. Ipsa voluptates dolor rerum fugiat sunt est dolor non earum.',
    categoryId: '35188',
    serviceGroupId: '86468',
  },
];
